[project]
name = "reading-the-road"
version = "1.0.0"
description = "AI-powered road safety analysis system"
requires-python = ">=3.13,<3.15"

dependencies = [
    "fastapi[standard]",
    "uvicorn",
    "numpy",
    "opencv-python-headless",
    "pillow",
    "torch",
    "torchvision",
    "transformers",
    "ultralytics",
    "huggingface-hub",
    "safetensors",
    "python-multipart"
]

[tool.fastapi]
entrypoint = "backend.main:app"